name: Front-end Build

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  Next-Build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd web && npm ci
      - name: Build
        run: cd web && npm run build